// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ7gi9rXTvgwWAnIgsXZPus9o8qwtklos',
    appId: '1:52591950022:web:97626a81b391bd86a43fc7',
    messagingSenderId: '52591950022',
    projectId: 'meddeck-4cb95',
    authDomain: 'meddeck-4cb95.firebaseapp.com',
    storageBucket: 'meddeck-4cb95.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPd1D_-yjo53Lx0wx4MtlJYjOVBbTxs-w',
    appId: '1:52591950022:android:5ed32ca8f4056d5ba43fc7',
    messagingSenderId: '52591950022',
    projectId: 'meddeck-4cb95',
    storageBucket: 'meddeck-4cb95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl-h65aU_4XY8f5HWTKGOkSuUkI5umSqo',
    appId: '1:52591950022:ios:a9fb3fd3354244f8a43fc7',
    messagingSenderId: '52591950022',
    projectId: 'meddeck-4cb95',
    storageBucket: 'meddeck-4cb95.firebasestorage.app',
    iosBundleId: 'com.example.meddeck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl-h65aU_4XY8f5HWTKGOkSuUkI5umSqo',
    appId: '1:52591950022:ios:a9fb3fd3354244f8a43fc7',
    messagingSenderId: '52591950022',
    projectId: 'meddeck-4cb95',
    storageBucket: 'meddeck-4cb95.firebasestorage.app',
    iosBundleId: 'com.example.meddeck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ7gi9rXTvgwWAnIgsXZPus9o8qwtklos',
    appId: '1:52591950022:web:7487deb30e160984a43fc7',
    messagingSenderId: '52591950022',
    projectId: 'meddeck-4cb95',
    authDomain: 'meddeck-4cb95.firebaseapp.com',
    storageBucket: 'meddeck-4cb95.firebasestorage.app',
  );

}